require File.dirname(__FILE__) + '/../generated/instructions.rb'
autoload :Assembler, File.dirname(__FILE__) + '/assembler/assembler.rb'
autoload :AssemblyDescriptorGenerator, File.dirname(__FILE__) + '/assembler/assembly_descriptor_generator.rb'
autoload :Disassembler, File.dirname(__FILE__) + '/assembler/disassembler.rb'
autoload :ExpressionParser, File.dirname(__FILE__) + '/assembler/expression_parser.rb'
autoload :Instruction, File.dirname(__FILE__) + '/assembler/instruction/instruction.rb'
autoload :MetaInstruction, File.dirname(__FILE__) + '/assembler/instruction/instruction.rb'
autoload :CpuInstruction, File.dirname(__FILE__) + '/assembler/instruction/instruction.rb'
autoload :InstructionParser, File.dirname(__FILE__) + '/assembler/instruction_parser.rb'
autoload :MixCore, File.dirname(__FILE__) + '/mix_core.rb'
autoload :Register, File.dirname(__FILE__) + '/register.rb'
autoload :Big, File.dirname(__FILE__) + '/register.rb'
autoload :Small, File.dirname(__FILE__) + '/register.rb'
autoload :Jump, File.dirname(__FILE__) + '/register.rb'
autoload :Limits, File.dirname(__FILE__) + '/word.rb'
autoload :Sign, File.dirname(__FILE__) + '/word.rb'
autoload :WordFunctions, File.dirname(__FILE__) + '/word.rb'
autoload :Word, File.dirname(__FILE__) + '/word.rb'
